### ISSUE TITLE
Request error with api/conversation/route.ts

### ISSUE THREAD

**Issue by AhmedBlackEye** [AntonioErdeljac/next13-ai-saas#13]
I'm getting this error from `api/conversation/route.ts`: `error No HTTP methods exported in '/workspace/AI_SAAS/app/api/conversation/route.ts'. Export a named export for each HTTP method.`. 
I'm also getting this error on the client side: `{
    "message": "Request failed with status code 405",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 405\n    at settle (webpack-internal:///(app-pages-browser)/./node_modules/axios/lib/core/settle.js:24:12)\n    at XMLHttpRequest.onloadend (webpack-internal:///(app-pages-browser)/./node_modules/axios/lib/adapters/xhr.js:121:66)",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/json"
        },
        "method": "post",
        "url": "/api/conversation",
        "data": "{\"messages\":[{\"role\":\"user\",\"content\":\"what is the radius of the sun?\"}]}"
    },
    "code": "ERR_BAD_REQUEST",
    "status": 405
}`
Here's the file: (sorry, for some reason code styling is not formatted correctly)
`import { auth } from "@clerk/nextjs";
import { NextResponse } from "next/server";
import { Configuration, OpenAIApi } from "openai";

const configuration = new Configuration({
  apiKey: process.env.OPENAI_API_KEY,
});

const openai = new OpenAIApi(configuration);

export async function Post(req: Request) {
  console.log(req);
  try {
    const { userId } = auth();
    const body = await req.json();
    const { messages } = body;
    console.log(messages);

    if (!userId) {
      return new NextResponse("Unauthorized", { status: 401 });
    }
    if (!configuration.apiKey) {
      return new NextResponse("OpenAI API key not configured", { status: 500 });
    }
    if (!messages) {
      return new NextResponse("Messages are required", { status: 400 });
    }
    const response = await openai.createChatCompletion({
      model: "gpt-3.5-turbo",
      messages,
    });

    return NextResponse.json(response.data.choices[0].message);
  } catch (err) {
    console.log("CONVERSATION ERROR", err);
    return new NextResponse("Internal error", { status: 500 });
  }
}
`

**Comment by AhmedBlackEye** [comment]
Never mind, my mistake was that I didn't capitalise the name of the function: 
`export async function POST(req: Request)`

**Comment by kivilaid** [comment]
https://github.com/openai/openai-node/discussions/217
