### ISSUE TITLE
Cancelling paid plans (frontend and db)

### ISSUE THREAD

**Issue by Kulaneian** [AntonioErdeljac/next13-ai-saas#19]
On the stripe side of things the plans get cancelled, when a user clicks on cancel subscription, but in the database and the frontend that doesn't happen. I followed the tutorial, but I just realized that users, will still see that they are on a paid plan after cancelling the plan.

**Comment by IgnatG** [comment]
I'm having the same issue. it would be good to understand how this can be fixed

**Comment by Kulaneian** [comment]
For that you need to modify the schema.prisma first to add a plan. Then in the route.ts for the subscription you need to add function to change the plan in the database and call that function. And on the frontend render the change so that the user can see the plan is cancelled and will not be there next month.

**Comment by Johann1987** [comment]
Hey :) 

If you got any model fro the schema prisma and the route to fix that, it would be great :)

**Comment by Kulaneian** [comment]
Just add a plan field to the user model. And modify that with your backend logic depending on frontend actions.
