### ISSUE TITLE
No response from chat, just showing No conversation started.

### ISSUE THREAD

**Issue by marksikaundi** [AntonioErdeljac/next13-ai-saas#7]
@AntonioErdeljac can you help, I have clearly followed the steps you used to build but I have a challenge once I type a question I want to get answers, to result is displaying, you can please help me

**Comment by janareddyc7** [comment]
Maybe its your openai keys

**Comment by marksikaundi** [comment]
> Maybe its your openai keys

yes i noticed that and fixed the issue
